# This is the compose file for the v1 branch of SurrealDB. It is used for the CI pipeline and can also be used for local development.

services:
  grafana:
    container_name: grafana
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.1}
        # remove the following line when developing to have backend debugger
        development: "false"
    ports:
      - 3000:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafanalabs-surrealdb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-surrealdb-datasource
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GF_LOG_LEVEL=debug
    networks:
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:v1.5.4@sha256:36ce1c22a65a60eb09c8978680573cc6848f2d3aa109472840c6e1974a75c237
    container_name: surrealdb
    restart: always
    command: start --username root --password test --allow-all
    ports:
      - 8000:8000
    networks:
      - surrealdb
  test-data-loader:
    image: curlimages/curl:latest@sha256:463eaf6072688fe96ac64fa623fe73e1dbe25d8ad6c34404a669ad3ce1f104b6
    container_name: test-data-loader
    command: |
      -v -X POST -u 'root:test' -H 'NS: test' -H 'DB: test' -H 'Accept: application/json' --data-binary @/dev/shm/surreal-deal-store.surql http://surrealdb:8000/import
    depends_on:
      - surrealdb
    restart: on-failure
    volumes:
      - ./tests/fixtures/surreal-deal-store.surql:/dev/shm/surreal-deal-store.surql
    networks:
      - surrealdb

networks:
  surrealdb:
