name: Commitlint

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    name: Check PR title conforms to @commitlint/config-conventional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo $PR_TITLE | yarn commitlint
